### PR TITLE
build(whiskers): remove `capitalize_hex` & update to v2.5.0

### PR DESCRIPTION
**Pull request by stenehall**
This replaces the depricated `capitalize_hex` with  `hex_format`

### CODE REVIEW

**Review by sgoudham — CHANGES_REQUESTED** [review]
You'll need to bump up the version too since it looks like `hex_format` was only introduced in [v2.4.0](https://github.com/catppuccin/whiskers/releases/tag/v2.4.0)

**Comment by stenehall** [comment]
> You'll need to bump up the version too since it looks like `hex_format` was only introduced in [v2.4.0](https://github.com/catppuccin/whiskers/releases/tag/v2.4.0)

You're right. My bad. I thought the version in the whiskers block would have warned me if I used something not allowed in that version. But I have 2.5 installed, it was introduced in 2.4 and the file said 2.3. So it seems like there's no built in check for this :).

I bumpbed the version in the files and added it as a separate commit before replacing the depricated `capitalize_hex`.

**Comment by uncenter** [comment]
The `whiskers.version` property is more like a minimum supported version (MSV). We don't have a list of features/changes/etc stored internally in Whiskers, so we can't warn if you use something that doesn't match the MSV. The version check comes in if you were to set the version to something newer than your local version of Whiskers, like `2.6.0` at the time of writing. If you try to build the file, you should get a compatibility error/warning that the template requires a newer version of Whiskers.

**Review by sgoudham — APPROVED** [review]
Thanks for updating the version!

FWIW, the list of commits in the PR doesn't matter too much as we prefer/require squash commits across the entire organisation when merging.

**Pull request merged**
